steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/immogule', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/immogule']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'immogule', '--image', 'gcr.io/$PROJECT_ID/immogule', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/$PROJECT_ID/immogule'
